### ISSUE TITLE
Unraid Docker error

### ISSUE THREAD

**Issue by dwightstanley** [pradeepmouli/homebridge-isy-js#9]
Using this Unraid Docker:
SiwatINC/unraid-ca-repository 
[https://github.com/SiwatINC/unraid-ca-repository](url)

Works fine with rodtoll/homebridge-isy-js

Throws this error with plugin as follows:
+ homebridge-isy-maker@0.2.0
+ homebridge-camera-ffmpeg@0.1.17
+ homebridge-isy@0.5.0-beta.20
+ homebridge-info@1.2.0
added 215 packages from 237 contributors in 16.602s
[4/29/2020, 5:13:55 PM] Loaded config.json with 0 accessories and 4 platforms.
[4/29/2020, 5:13:55 PM] ---
[4/29/2020, 5:13:56 PM] Loaded plugin: homebridge-camera-ffmpeg
[4/29/2020, 5:13:56 PM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[4/29/2020, 5:13:56 PM] ---
[4/29/2020, 5:13:56 PM] Loaded plugin: homebridge-config-ui-x
[4/29/2020, 5:13:56 PM] Registering platform 'homebridge-config-ui-x.config'
[4/29/2020, 5:13:56 PM] ---
[4/29/2020, 5:13:56 PM] Loaded plugin: homebridge-info
[4/29/2020, 5:13:56 PM] Registering platform 'homebridge-info.Info'
[4/29/2020, 5:13:56 PM] ---
[4/29/2020, 5:13:56 PM] ====================
[4/29/2020, 5:13:56 PM] ERROR LOADING PLUGIN homebridge-isy:
[4/29/2020, 5:13:56 PM] Error: Cannot find module '/usr/local/lib/node_modules/homebridge'
Require stack:
- /usr/lib/node_modules/homebridge-isy/dist/plugin.js
- /usr/lib/node_modules/homebridge/lib/plugin.js
- /usr/lib/node_modules/homebridge/lib/server.js
- /usr/lib/node_modules/homebridge/lib/cli.js
- /usr/lib/node_modules/homebridge/bin/homebridge
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
at Function.Module._load (internal/modules/cjs/loader.js:686:27)
at Module.require (internal/modules/cjs/loader.js:848:19)
at require (internal/modules/cjs/helpers.js:74:18)
at Object.<anonymous> (/usr/lib/node_modules/homebridge-isy/dist/plugin.js:7:22)
at Module._compile (internal/modules/cjs/loader.js:955:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
at Module.load (internal/modules/cjs/loader.js:811:32)
at Function.Module._load (internal/modules/cjs/loader.js:723:14)
at Module.require (internal/modules/cjs/loader.js:848:19)
[4/29/2020, 5:13:56 PM] ====================
[4/29/2020, 5:13:56 PM] Loaded plugin: homebridge-camera-ffmpeg
[4/29/2020, 5:13:56 PM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[4/29/2020, 5:13:56 PM] ---
[4/29/2020, 5:13:56 PM] Loaded plugin: homebridge-config-ui-x
[4/29/2020, 5:13:56 PM] Registering platform 'homebridge-config-ui-x.config'
[4/29/2020, 5:13:56 PM] ---
[4/29/2020, 5:13:56 PM] Loaded plugin: homebridge-info
[4/29/2020, 5:13:56 PM] Registering platform 'homebridge-info.Info'
[4/29/2020, 5:13:56 PM] ---
[4/29/2020, 5:13:56 PM] ====================
[4/29/2020, 5:13:56 PM] ERROR LOADING PLUGIN homebridge-isy:
[4/29/2020, 5:13:56 PM] Error: Cannot find module '/usr/local/lib/node_modules/homebridge'
Require stack:
- /usr/lib/node_modules/homebridge-isy/dist/plugin.js
- /usr/lib/node_modules/homebridge/lib/plugin.js
- /usr/lib/node_modules/homebridge/lib/server.js
- /usr/lib/node_modules/homebridge/lib/cli.js
- /usr/lib/node_modules/homebridge/bin/homebridge
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
at Function.Module._load (internal/modules/cjs/loader.js:686:27)
at Module.require (internal/modules/cjs/loader.js:848:19)
at require (internal/modules/cjs/helpers.js:74:18)
at Object.<anonymous> (/usr/lib/node_modules/homebridge-isy/dist/plugin.js:7:22)
at Module._compile (internal/modules/cjs/loader.js:955:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
at Module.load (internal/modules/cjs/loader.js:811:32)
at Function.Module._load (internal/modules/cjs/loader.js:723:14)
at Module.require (internal/modules/cjs/loader.js:848:19)
[4/29/2020, 5:13:56 PM] ====================
[4/29/2020, 5:13:56 PM] Loaded plugin: homebridge-isy-maker
homebridge API version: 2.4
[4/29/2020, 5:13:56 PM] Registering platform 'homebridge-isy-maker.isy-maker'
[4/29/2020, 5:13:56 PM] ---
[4/29/2020, 5:13:56 PM] Loading 4 platforms...
[4/29/2020, 5:13:56 PM] Error: The requested platform 'isy-js' was not registered by any plugin.
at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:134:13)
at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:327:45)
at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:90:36)
at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (internal/modules/cjs/loader.js:955:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
at Module.load (internal/modules/cjs/loader.js:811:32)
at Function.Module._load (internal/modules/cjs/loader.js:723:14)
at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
[4/29/2020, 5:13:56 PM] Got SIGTERM, shutting down Homebridge...

Is this due to the container not being on the beta?
This docker installs as Version 0.4.53 - after it is running it updates to 1.03 but i can't get it to start to update
To use this docker the plugins are indicated on the docker pull.

**Comment by apnar** [comment]
Have you tried the "official" docker container for homebridge here:

https://github.com/oznu/docker-homebridge

**Comment by apnar** [comment]
Looks like the SiwatINC images install homebridge globally with "npm -g" while the official repo above installs them in /usr/local/lib.  Pradeep just pushed a fix yesterday for issue number 7 (paths in official docker container) that may have broken the paths in some other containers.

I'd definitely suggest trying the official image I linked to above.  It adds the GUI in and has some nice management features around it.

**Comment by dwightstanley** [comment]
Thanks - I will try that docker.

**Comment by pradeepmouli** [comment]
try the latest update - homebridge-isy imports homebridge & hap-nodesjs as modules. I've added a post install script that tries to find the installation path of homebridge and hap-nodes, wherever it is, and updates the source files.

**Comment by dwightstanley** [comment]
Cannot install sing this Unraid Docker:
SiwatINC/unraid-ca-repository
https://github.com/SiwatINC/unraid-ca-repository
Just too many errors. 
Will try using a different docker (I like HOOBS)

**Comment by dwightstanley** [comment]
Trying to use oznu/homebridge docker with this plugin - getting a whole bunch of different errors now - no devices showing under Accessories for this plugin
[Homebridge-isy-oznu.log.txt](https://github.com/pradeepmouli/homebridge-isy-js/files/4566118/Homebridge-isy-oznu.log.txt)

**Comment by pradeepmouli** [comment]
Looks like the issue here is that Guest Bedroom Light Switch (53 D5 A1 1) has blank notes (no location or spoken name) and is not in a folder.  I’ll work on handling this better, but if you update your config to have a deviceNameRules entry as below:

 "deviceNameRules":
            {
                "format":"${location ?? folder ?? ' '} ${spokenName ?? name}"
            },

this should fix the issue.

**Comment by dwightstanley** [comment]
I added a spoken name to that device - also added your code to config.
It throws errors still but completes. The names are not working properly at all.
using the Rodtoll plugin and looking at the device properties has much useful information.
This plugin seems to be different and data is different.
Anything you can do to help sort this out for me?
[config.json.txt](https://github.com/pradeepmouli/homebridge-isy-js/files/4568312/config.json.txt)
[Homebridge-isy-oznu.log.txt](https://github.com/pradeepmouli/homebridge-isy-js/files/4568313/Homebridge-isy-oznu.log.txt)
![Screenshot Rodtoll](https://user-images.githubusercontent.com/25987898/80870754-edb43680-8c7e-11ea-97d3-6eb0bb54461c.png)
![Screenshot Pradeepmouli](https://user-images.githubusercontent.com/25987898/80870757-f573db00-8c7e-11ea-9ad1-a4181d74a3fd.png)

**Comment by dwightstanley** [comment]
Also want to mention that I have a scene with one switch. 
Clicking the scene button illuminates the switch but not the scene. 
The scene remains dark and does not toggle the switch off - only on.

**Comment by dwightstanley** [comment]
> Using this Unraid Docker:
> SiwatINC/unraid-ca-repository
> [https://github.com/SiwatINC/unraid-ca-repository](url)
> 
> Works fine with rodtoll/homebridge-isy-js
> 
The missing plugin.js is located in this docker at:
./usr/lib/node_modules/homebridge/lib/plugin.js

**Comment by dwightstanley** [comment]
Ok - I tried your plugin on Unraid using the Homebridge-oznu container. As soon as i restart with your plugin it throws errors and Homebridge crashes.
Attached are the files for you to look at.

[config.json.txt](https://github.com/pradeepmouli/homebridge-isy-js/files/4840909/config.json.txt)
[ISYNodesDump.json.txt](https://github.com/pradeepmouli/homebridge-isy-js/files/4840910/ISYNodesDump.json.txt)
[package.json.txt](https://github.com/pradeepmouli/homebridge-isy-js/files/4840911/package.json.txt)

Hope this helps

**Comment by dwightstanley** [comment]
Abandoned this plugin for the ‘old’ Rodtoll until it becomes necessary to change that one
